test: &default

  # Credentials for REST APIs
  client_id: EBWKjlELKMYqRNQ6sYvFo64FtaRLRR5BdHEESmha49TM
  client_secret: EO422dn3gQLgDbuwqTjzrFgFtaRLRR5BdHEESmha49TM

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: stasandrichuk9-facilitator_api1.gmail.com
  password: ND7FFVQP248FRUQ6
  signature: AJRp6hfUq.88q9-chrvtYjEI9FskA40Aqc.TMhdRD3esIQ7EWbqJRV8u
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: stasandrichuk9-facilitator@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

  # verbose_logging: true

development:
  <<: *default

production:
  <<: *default
  mode: live
